### ISSUE TITLE
set ε move in gui?

### ISSUE THREAD

**Issue by mlibre** [rindPHI/FSAUtilsGUI#1]
how to set ε move in gui or xml filein NFA?

**Comment by rindPHI** [comment]
Unfortunately, FSAUtils does currently not support the empty word as input. I simply forgot this case when I created the underlying data models! Unfortunately, I currently don't have the time of extending FSAUtils, so the best way would be to fork the project and hack it in yourself if you got the time...

**Comment by mlibre** [comment]
thanks
